# Generated by Django 4.2.11 on 2024-04-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="subevents",
            field=models.ManyToManyField(blank=True, default=None, to="users.event"),
        ),
        #migrations.DeleteModel(name="Subevent",),
    ]
