# Generated by Django 4.2.11 on 2024-04-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_event_subevents_delete_subevent"),
    ]
