# Generated by Django 4.2.11 on 2024-04-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_delete_subevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_subevent",
            field=models.BooleanField(default=False),
        ),
        #migrations.DeleteModel(name="Subevent",),
    ]
