# Generated by Django 4.2.11 on 2024-04-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_event_is_subevent_delete_subevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='subevents',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='users.event'),
        ),
        migrations.DeleteModel(
            name='Subevent',
        ),
        migrations.AddField(
            model_name='eventsequence',
            name='events',
            field=models.ManyToManyField(to='users.event'),
        ),
    ]
